# Generated by Django 2.1.4 on 2019-03-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litigations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='litigation',
            name='organizations',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='litigation',
            name='people',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
